Repository DSD-DBS/capella-collab-manager, pull requests merged in 2022-09, with the labels that each got.

#219 Actions
  .github/workflows/lint.yml
  .github/workflows/push.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  README.md
  backend/Makefile
  backend/generate_git_archival.py
  backend/t4cclient/alembic/env.py
  backend/t4cclient/alembic/versions/0a16fb85f762_add_t4c_username_to_ease_backup.py
  backend/t4cclient/alembic/versions/1b4c1dc944d6_remove_rdp_username.py
  backend/t4cclient/alembic/versions/279ec954b302_session_add_passwords_for_rdp_and_.py
  backend/t4cclient/alembic/versions/377b60de4441_link_git_repositories_with_projects.py
  backend/t4cclient/alembic/versions/52aec4f341a5_use_repository_name_instead_of_.py
  backend/t4cclient/alembic/versions/687484695147_add_persistent_enum.py
  backend/t4cclient/alembic/versions/6a8bdec1dccb_add_databaseproject.py
  backend/t4cclient/alembic/versions/9259062f0f62_remove_unique_constraint_for_project.py
  backend/t4cclient/alembic/versions/bfafdd03e30c_add_git_models_for_repositories.py
  backend/t4cclient/alembic/versions/caa0ecb7b28d_add_ease_backup_table.py
  backend/t4cclient/alembic/versions/d6a23ac7f263_add_credentials_for_gitmodels.py
  backend/t4cclient/alembic/versions/d7fe491603c3_add_cascades.py
  backend/t4cclient/alembic/versions/f3efdcedfdde_add_read_write_access.py
  backend/t4cclient/alembic/versions/fc6250459067_use_project_id_as_reference_instead_of_.py
  backend/t4cclient/config/__init__.py
  backend/t4cclient/config/diff.py
  backend/t4cclient/config/loader.py
  backend/t4cclient/core/authentication/__init__.py
  backend/t4cclient/core/authentication/database/__init__.py
  backend/t4cclient/core/authentication/database/git_models.py
  backend/t4cclient/core/authentication/database/jenkins.py
  backend/t4cclient/core/authentication/provider/azure/keystore.py
  backend/t4cclient/core/authentication/provider/azure/routes.py
  backend/t4cclient/core/authentication/provider/oauth/flow.py
  backend/t4cclient/core/authentication/provider/oauth/keystore.py
  backend/t4cclient/core/authentication/provider/oauth/routes.py
  backend/t4cclient/core/credentials.py
  backend/t4cclient/core/database/__main__.py
  backend/t4cclient/core/database/repositories.py
  backend/t4cclient/core/database/repository_users.py
  backend/t4cclient/core/services/repositories.py
  backend/t4cclient/extensions/__init__.py
  backend/t4cclient/extensions/backups/ease/crud.py
  backend/t4cclient/extensions/backups/ease/routes.py
  backend/t4cclient/extensions/modelsources/git/crud.py
  backend/t4cclient/extensions/modelsources/git/models.py
  backend/t4cclient/extensions/modelsources/git/routes.py
  backend/t4cclient/extensions/modelsources/t4c/connection.py
  backend/t4cclient/routes/notices.py
  backend/t4cclient/routes/repositories/__init__.py
  backend/t4cclient/routes/repositories/users.py
  backend/t4cclient/routes/users.py
  backend/t4cclient/sessions/database.py
  backend/t4cclient/sessions/operators/__init__.py
  backend/t4cclient/sessions/operators/k8s.py
  backend/t4cclient/sessions/routes.py
  frontend/fetch-version.ts
  helm/templates/mock/licence.deployment.yaml
  helm/templates/mock/t4c.deployment.yaml
  helm/values.yaml
Labels: enhancement, priority:low, effort:medium

#227 Improve error message handling
  backend/capellacollab/core/authentication/database/__init__.py
  backend/capellacollab/core/authentication/database/jenkins.py
  backend/capellacollab/core/authentication/jwt_bearer.py
  backend/capellacollab/projects/users/routes.py
  backend/capellacollab/routes/users.py
  backend/capellacollab/sessions/files/routes.py
  backend/capellacollab/sessions/routes.py
  backend/capellacollab/settings/modelsources/git/routes.py
  backend/capellacollab/utils/git_utils.py
  frontend/src/app/auth/http-interceptor/auth.interceptor.ts
Labels: enhancement, version:v2

#254 dics: Fix broken hyperlink to license file
  README.md
Labels: documentation

#253 V1/docs getting started with t4c project
  docs/user/docs/getting-started/capella-intro.md
  docs/user/docs/getting-started/getting-started.md
  docs/user/docs/getting-started/read-only.md
  docs/user/docs/getting-started/read-write-t4c.md
  docs/user/docs/getting-started/screenshots/cap-conn-remote-model.jpg
  docs/user/docs/getting-started/screenshots/cap-conn-remote-model.jpg.license
  docs/user/docs/getting-started/screenshots/cap-test-conn.jpg
  docs/user/docs/getting-started/screenshots/cap-test-conn.jpg.license
  docs/user/docs/getting-started/screenshots/connect-pw.jpg
  docs/user/docs/getting-started/screenshots/connect-pw.jpg.license
  docs/user/docs/getting-started/screenshots/connection-example.jpg
  docs/user/docs/getting-started/screenshots/connection-example.jpg.license
  docs/user/docs/getting-started/screenshots/pers-workspace.jpg
  docs/user/docs/getting-started/screenshots/pers-workspace.jpg.license
  docs/user/docs/getting-started/screenshots/profile-settings.jpg
  docs/user/docs/getting-started/screenshots/profile-settings.jpg.license
  docs/user/docs/getting-started/screenshots/read-only.jpg
  docs/user/docs/getting-started/screenshots/read-only.jpg.license
  docs/user/docs/getting-started/screenshots/repo-pwd-setting.jpg
  docs/user/docs/getting-started/screenshots/repo-pwd-setting.jpg.license
  docs/user/docs/index.md
  docs/user/docs/onboarding.md
  docs/user/docs/projects/roles.md
  docs/user/mkdocs.yml
Labels: documentation

#252 K3d deployment and workflow improvements
  Makefile
  backend/capellacollab/extensions/modelsources/t4c/connection.py
  backend/capellacollab/sessions/routes.py
  frontend/.gitignore
  frontend/package.json
  frontend/src/environments/environment.dev.ts
  frontend/src/proxy.conf.js
  helm/config/backend.yaml
Labels: version:v2
